{% set name = "pybind11-stubgen" %}
{% set version = "2.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sizmailov/pybind11-stubgen/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5651ce8f598f304e25db0d69382e46d4ff16538039cb677c444b9c1c3875aaf1

build:
  number: 1
  noarch: python
  entry_points:
    - pybind11-stubgen = pybind11_stubgen.__init__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pybind11_stubgen
  commands:
    - pip check
    - pybind11-stubgen --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/sizmailov/pybind11-stubgen
  summary: PEP 561 type stubs generator for pybind11 modules
  license: BSD-Protection
  license_file: LICENSE

extra:
  recipe-maintainers:
    - allanleal
    - ken-lauer
